export const GET_USERS = "GET_USERS";
export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_SINGLE_USER_ERROR = "GET_SINGLE_USER_ERROR";
export const GET_SINGLE_USER_LOADING = "GET_SINGLE_USER_LOADING";
